"""initial_migration

Revision ID: e5ff87203f0f
Revises: 
Create Date: 2023-02-07 12:24:25.472342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ff87203f0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_by', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('date', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('date')
        batch_op.drop_column('comment_by')

    # ### end Alembic commands ###
